---
spring:
  profiles: dev

debug: false
logging:
  level:
    root: info

eureka:
  instance:
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://root:root@localhost:9001/eureka/

ribbon:
  # 请求连接的超时时间 默认的时间为 1 秒
  ConnectTimeout: 10000
  # 请求处理的超时时间
  ReadTimeout: 10000
  # 切换实例的重试次数
  MaxAutoRetriesNextServer: 0
  # 对当前实例的重试次数
  MaxAutoRetries: 2
  # 对所有操作请求都进行重试
  OkToRetryOnAllOperations: true

feign:
  client:
    config:
      default:
        # 请求连接的超时时间 默认的时间为 1 秒
        connectTimeout: 10000
        # 请求处理的超时时间
        readTimeout: 10000
  hystrix:
    enabled: true

info:
  spring:
    application:
      name: ${spring.application.name}
  server:
    port: ${server.port}