---
spring:
  profiles: dev

  datasource:
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///hydrogen_mall?serverTimezone=Asia/Shanghai
    username: root

  rabbitmq:
    password: admin
    port: 5672
    host: 118.178.194.239
    username: admin

  redis:
    password: root
    port: 6379
    jedis:
      pool:
        max-idle: 500
        min-idle: 0
        max-active: 2000
        max-wait: 3000ms
    host: 118.178.194.239

mybatis:
  configuration:
    map-underscore-to-camel-case: true

mapper:
  identity: MYSQL
  mapper-locations: mybatis/mapper/*Mapper.xml