---
spring:
  profiles: dev
  application:
    name: hmall-order-service

  datasource:
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///hydrogen_mall?serverTimezone=Asia/Shanghai
    username: root

  rabbitmq:
    password: admin
    port: 5672
    host: 118.178.194.239
    username: admin

  redis:
    password: root
    port: 6379
    jedis:
      pool:
        max-idle: 500
        min-idle: 0
        max-active: 2000
        max-wait: 3000ms
    host: 118.178.194.239

server:
  port: 7031
debug: false

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://root:root@localhost:9001/eureka/

mybatis:
  configuration:
    map-underscore-to-camel-case: true

ribbon:
  # 请求连接的超时时间 默认的时间为 1 秒
  ConnectTimeout: 10000
  # 请求处理的超时时间
  ReadTimeout: 10000
  # 切换实例的重试次数
  MaxAutoRetriesNextServer: 0
  # 对当前实例的重试次数
  MaxAutoRetries: 2
  # 对所有操作请求都进行重试
  OkToRetryOnAllOperations: true

feign:
  client:
    config:
      default:
        # 请求连接的超时时间 默认的时间为 1 秒
        connectTimeout: 10000
        # 请求处理的超时时间
        readTimeout: 10000

logging:
  level:
    root: info

mapper:
  identity: MYSQL

info:
  spring:
    application:
      name: ${spring.application.name}
  server:
    port: ${server.port}
