---
spring:
  application:
    name: hmall-ware-web
  profiles: dev

server:
  port: 8031
debug: false

eureka:
  instance:
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://root:root@localhost:9001/eureka/

#全局配置
ribbon:
  # 请求连接的超时时间 默认的时间为 1 秒
  ConnectTimeout: 5000
  # 请求处理的超时时间
  ReadTimeout: 5000

#局部配置
ego-product-providert:
  ribbon:
    # 切换实例的重试次数
    MaxAutoRetriesNextServer: 0
ego-product-provider:
  ribbon:
    # 请求连接的超时时间
    ConnectTimeout: 3000
    # 对当前实例的重试次数
    MaxAutoRetries: 2
    # 请求处理的超时时间
    ReadTimeout: 3000
    # 对所有操作请求都进行重试
    OkToRetryOnAllOperations: true

logging:
  level:
    root: info

info:
  spring:
    application:
      name: ${spring.application.name}
  server:
    port: ${server.port}
